#!/usr/bin/python3
"""





#####################################################################
    kk

                        DO NOT EDIT THIS FILE


#####################################################################






"""

import unittest
from main import binomial_coefficient 

class Tests(unittest.TestCase):
    def test(self):
        self.assertEqual(binomial_coefficient(n=10, r=5),252)
        

if __name__=='__main__':
    unittest.main()
